name: Release

on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed
    branches: 
      - master 
      - main

permissions:
  contents: write

jobs:
  set-version-tag:
    if: ${{ github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v4
      # get version
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0
        with:
          versionSpec: '5.x'
      - name: Set SemVer Version
        uses: gittools/actions/gitversion/execute@v3.0
        id: gitversion

  release:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23-bullseye
    needs: set-version-tag
    env:
      SEMVER: ${{ needs.set-version-tag.outputs.semVer }}
      TASKCTL_CONFIG_FILE: tasks.yaml
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: set up git for tag pushing
        run: |
          apt-get update && apt-get install -y git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.email ${{ github.actor }}-ci@gha.org
          git config user.name ${{ github.actor }}

      - name: build binaries
        run: |
          echo "Version: v$SEMVER"
          echo "Revision: $GITHUB_SHA"
          go run cmd/main.go run pipeline build:binary --set Version=v${SEMVER} --set Revision=$GITHUB_SHA

      # tag repo
      - name: tag repo
        run: | 
          echo "REVISION  -> $GITHUB_SHA"
          echo "VERSION -> $GITVERSION_SEMVER"
          git tag -a "v${SEMVER}" -m "ci tag release" $GITHUB_SHA
          git push origin "v${SEMVER}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.set-version-tag.outputs.semVer }}
          # TODO: add additional info to the release
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./bin/*
